<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-11-09T10:41:11+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Portfolio',
        ],
    ],
];
